// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNDrj7tkQD7JUDz_N2XS6joidk7Mdbzk0',
    appId: '1:161860665390:web:c447524079c22bd8849fbf',
    messagingSenderId: '161860665390',
    projectId: 'evaluacion-96059',
    authDomain: 'evaluacion-96059.firebaseapp.com',
    storageBucket: 'evaluacion-96059.appspot.com',
    measurementId: 'G-ZTT54YNK93',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkg880c-zgSZUcjj1UG_8J-ZDwnfrgX-g',
    appId: '1:161860665390:android:5b267a0aa5b9a4dc849fbf',
    messagingSenderId: '161860665390',
    projectId: 'evaluacion-96059',
    storageBucket: 'evaluacion-96059.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXfj9SdwCXNdkTI2Thwu8FzkFnGflzBTE',
    appId: '1:161860665390:ios:922d643eac9696e7849fbf',
    messagingSenderId: '161860665390',
    projectId: 'evaluacion-96059',
    storageBucket: 'evaluacion-96059.appspot.com',
    iosBundleId: 'com.ro.evaluacion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXfj9SdwCXNdkTI2Thwu8FzkFnGflzBTE',
    appId: '1:161860665390:ios:42581bb0e3a6b1ab849fbf',
    messagingSenderId: '161860665390',
    projectId: 'evaluacion-96059',
    storageBucket: 'evaluacion-96059.appspot.com',
    iosBundleId: 'com.ro.evaluacion.RunnerTests',
  );
}
